# Generated by Django 4.0 on 2023-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sentiment_delete_sentimentanalysishistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputField', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
    ]
