# Generated by Django 4.0 on 2023-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_analyze_delete_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyze',
            name='sentimentField',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analyze',
            name='inputField',
            field=models.TextField(),
        ),
    ]
